kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: keycloak-admin-role
  annotations:
    argocd.argoproj.io/sync-wave: "3"
rules:
  - verbs:
      - '*'
    apiGroups:
      - 'keycloaks.keycloak.org'
    resources:
      - '*'

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: keycloak-admin-role-openshift-gitops-argocd-application-controller
  annotations:
    argocd.argoproj.io/sync-wave: "3"
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keycloak-admin-role
